### ISSUE TITLE
Create/locate up to-date docs on running BCGov apps on minishift

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#1020]
We should have a doc that describes some of the special steps required to run BC Gov apps on minishift 
(e.g. that might required BC Gov "platform" images).

Note: @w8896699  may already have created this

**Comment by patricksimonian** [comment]
yep. Its in this PR https://github.com/bcgov/devhub-resources/pull/17/files#diff-9aaf12b81d292dba1a8176468a2919f7. I think we will just need to test the instructions/polish it up a bit

**Comment by sheaphillips** [comment]
Note also that there is a doc at https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/OCP/run-openshift-on-own-computer.html that does describe this in some fashion, but maybe outdated and definitely is missing details of pulling images from Pathfinder, etc.

**Comment by patricksimonian** [comment]
ooh good to know. Sounds like some consolidation is in order.

**Comment by patricksimonian** [comment]
closing as this is stale
