### ISSUE TITLE
We should have some content that describes our OpenShift storage

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#1022]
Possible starting points/references:

https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/OCP/CNS.html
https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/OCP/IncreasePVCSize.html

**Comment by patricksimonian** [comment]
I do believe this exists now https://developer.gov.bc.ca/Persistent-Storage-Services
