### ISSUE TITLE
We should have content related to OpenShift maintenance/evac process

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#1023]
References/starting points:

 https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/OCP/NodeEvacuation.html

https://github.com/BCDevOps/openshift-wiki/wiki/Effect-on-Pods-with-Standard-Maintenance---Evacuate-Drain-Procedure

https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/OCP/EvacuationDrainProcedure.html

**Comment by lukegonis** [comment]
@patricksimonian another old issue, is it still relevant?

**Comment by mitovskaol** [comment]
I feel like this is already covered in our [Resiliency Guidelines](https://developer.gov.bc.ca/Resiliency-Guidelines) and [Post-outage Checklist](https://developer.gov.bc.ca/Post-Outage-Application-Health-Checklist)
