### ISSUE TITLE
We should include some content about practices related to databases (Postgres in particular)

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#1026]
Reference/starting points:

https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/DB/PostgresqlStartIssue.html
https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/DB/PostgresqlUnexpetedDataEOF.html
https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/DB/PostgresqlCrashLoopTupleError.html
https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/DB/PostgresqlStuckInRecovery.html
https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/DB/PostgreSQLBackupRestore.html

**Comment by mitovskaol** [comment]
The new content and the content org in DevHub will be developed as part of the DevHub revamp in 2021/2022. At that time we will identify what new content should be developed and published to DevHub.
