### ISSUE TITLE
Developer Experience Session 1

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#1054]
deliverables:
- backlog groom and prioritization
- a high level road map of items we want to complete by end of q4.
- a clear objective(s) for dev experience so that is measurable to see if we are hitting the target ? :thinking_face:
- a pecking list of things processes that annoy us that we can possibly improve or automate :)
- define a max amount of toil tasks allowed per week
  - what happens if we reach that limit? What do we do? (ask todd, shea)

- team rules for feature creation..._if you hvae to do an arduous task more than once_ it is time to think about creating a ticket to automate it.

**Comment by patricksimonian** [comment]
shall we set up a developer experience  session for tomorrow?
