### ISSUE TITLE
Migrate request channel to a github repo

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/devhub-app-web#1066]
- requester use a github template to create requests
- stop using the request channel
- hubot reminder user to move to github when post detected in channel

**Comment by ShellyXueHan** [comment]
Updates:
1. request repo ready
2. devhub docs ready
3. not using hubot at the moment, plan to leave a message and then mute the channel
4. need to be reviewed with @kelpisland before going ahead

**Comment by patricksimonian** [comment]
:fire:
