### ISSUE TITLE
Add tags to search index and improve scoring mechanism

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1081]
There are a few key improvements we could do to the search ux.

Firstly integrate tags into nodes so that they can be indexed by search.
Secondely more widely support labels for nodes and have specific labels that perform sorting/filtering functions. 

Ideally we should be able to 'group' resources by labels during a search and then order them correctly. 

Maybe we follow the openshift label mechanism for things like `app=<blah>`

**Comment by w8896699** [comment]
- [x] openshift label mechanism for things like app=devhub
- [ ] integrate tags into nodes so that they can be indexed by search.
- [ ]  more widely support labels for nodes and have specific labels that perform sorting/filtering functions.
