### ISSUE TITLE
Investigate Feasbility of leveraging Algolia with our architecture

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1135]
[Algolia](https://www.algolia.com/pricing/) is a search engine sass offering that will offload a lot of the heavy lifting we do around search. Given that our architecture has resulted in not having files local to our system. Let's see if Algolia will even work for us

Things to check:

- can we set up an account on algolia
- can we push content to it dynamically to build an index
- can we dynamically create indexes for a pr based work flow (similar to key claok client creatiion and deletion in our jenkins file)

Deliverables:

- a go/no-go on algolia

Notes:

Think outside the box, this may just require us to write a gatsby plugin to push content into algolia,...this plugin also may already exist!

**Comment by patricksimonian** [comment]
1. Setting up an account:

we can set up a Community account which is free and just limits the number of operations we can do per month. I say let's try out this model until it doesn't work. We will need to create an account for our Team so that it can be managed. For now, I've created a personal account for testing. 

Being a community tier user of Algolia, we would need to show the algolia brand in our search results
![search-by-algolia-light-background.svg](https://images.zenhubusercontent.com/5c2e50794feb4829c0135179/15c59d2a-ddfd-40b2-9372-e25de8c6a47d)

2 & 3. Dynamically build /remove indexes:

Yes! this is possible via the algolia API. Essentially `gatsby-plugin-algolia` would be responsible for creating indexes, and then we could refer to the index name . with the algolia api's delete index method to get rid of them. 

This would involve storing additional env specific variables in our build configs as well as adding algolia env vars to our jenkins pipeline so that the pipeline cli scripts could interact with the algolia api. 

3.

**Comment by patricksimonian** [comment]
in addition here is a great guide on https://www.gatsbyjs.org/docs/adding-search-with-algolia/

**Comment by patricksimonian** [comment]
![Algolia Devhub Search Architecture.png](https://images.zenhubusercontent.com/5c2e50794feb4829c0135179/377ae13e-2c95-4f79-8f9d-266321a3679c)

**Comment by sheaphillips** [comment]
There might be a different way of handling the indexes...can they be renamed and/or could we use a build number or something else instead of magic names for the index names?

**Comment by patricksimonian** [comment]
i agree. I think that was what I was trying to illustrate. The index names would be something like
`devhub-search-<prNumber>`
