### ISSUE TITLE
Investigate integrating appropriate meta tags for seacrhabiltiy/indexing of static sites with google

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1137]
Gatsby has the best practices documentation to make static sites more discoverable by search engines. This involves settings metatags where appropriate. 

There is a component called `react-helmet` which allows for dynamic head tag information to be loaded. This should be leveraged in conjunction with this doc https://www.gatsbyjs.org/docs/add-page-metadata/

**Comment by w8896699** [comment]
![Screen Shot 2019-11-26 at 10.34.14 AM.png](https://images.zenhubusercontent.com/5d6ffb905ec50a5aa4201bcb/768e25eb-5a81-47da-85db-e3470e7c0877)

**Comment by w8896699** [comment]
Now SEO is 90

**Comment by w8896699** [comment]
![Screen Shot 2019-11-28 at 10.01.14 AM.png](https://images.zenhubusercontent.com/5d6ffb905ec50a5aa4201bcb/ea0ee6cb-72ee-4a94-ad1e-bfdeacc37874)

**Comment by w8896699** [comment]
Now we have 100 SEO!!!

**Comment by w8896699** [comment]
The further step to increase searchability will be authenticated with google by adding their script to DevHub. But considering that Google is probably not how our user will find resources on DevHub, this may not necessary.
