### ISSUE TITLE
investigate best approach to work with algolia and search gate

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1138]
Having two separate searches (Algolia and Searchgate) seems odd and perhaps even a counter pattern. What are some options that we could look at when leveraging these two search sources? Is this purely a UI/UX challenge or should we aim to federate search through search gate?

@sheaphillips

**Comment by sheaphillips** [comment]
I imagined we would do it through search gate...

**Comment by patricksimonian** [comment]
I feel like we'll have to really take a look at how to improve search gate then so we are not producing 'blocking' searches through this type of federation? I think algoliia is pretty snappy and has some built in features for auto suggest

**Comment by sheaphillips** [comment]
good point.  I think it would be fine to have algolia and its schmancy auto
suggest features as the primary search, with search gate searches happening
upon submission and/or optionally.

**Comment by patricksimonian** [comment]
i agree, i think thats a good start. That being said I just discovered... https://blog.apollographql.com/new-features-in-graphql-batch-defer-stream-live-and-subscribe-7585d0c28b07

Some amazing features for apollo. If we have cycles search gate should definitely have __defers__ and streaming searches

**Comment by w8896699** [comment]
In conclusion, the best way, for now, is to let them run separately!
