### ISSUE TITLE
The main page css is not correct

### ISSUE THREAD

**Issue by w8896699** [bcgov/devhub-app-web#1149]
<img width="1680" alt="Screen Shot 2019-11-27 at 3 23 38 PM" src="https://user-images.githubusercontent.com/22565041/69765748-0ea1ba00-112a-11ea-9f15-aa4f4371337f.png">
The css comonent seems not correct in dev after the first search, after hard referesh, it's gone

**Comment by patricksimonian** [comment]
how do you reproduce this?

**Comment by patricksimonian** [comment]
I have a feeling that this is not a cacheing issue. Rather emotion js is confusing class names on fresh renders of the page. Perhaps we have styled components that are named the same
