### ISSUE TITLE
Card with no description

### ISSUE THREAD

**Issue by kelpisland** [bcgov/devhub-app-web#1175]
![image](https://user-images.githubusercontent.com/9368818/70474934-58729480-1a88-11ea-8295-bc0887424da9.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by patricksimonian** [comment]
We will need to contact the organizers of that event to update their information

**Comment by patricksimonian** [comment]
doesn't appear to be an issue any longer :)
