### ISSUE TITLE
add Date to all Event topic cards in Devhub 

### ISSUE THREAD

**Issue by jeff-card** [bcgov/devhub-app-web#1181]
**Is your feature request related to a problem? Please describe.**
I was reviewing upcoming events in Devhub and thought it would be great to have the date show up in the topic card without having to navigate to eventbrite or meetup for each event to determine when it's happening.

**Describe the solution you'd like**
Put the date in a consistent location on each topic card

**Describe alternatives you've considered**
Leave it as is

**Additional context**
None

**Comment by patricksimonian** [comment]
#1180 beat you to it 😏
