### ISSUE TITLE
Create a process/flow diagram for an automated content contribution model

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1256]
## Summary

The Devhub's content contribution model is great for Developers. A pull request is made to `JSON` formatted files and then pages are generated on the Devhub. The Challenge is that there are many users who haven't and shouldn't have too learn about Github processes such as PR's to suggest content in the Devhub. 

The purpose for this issue is to find a solution to this issue. 

## Outcomes

- a vision for what a better contribution model could be
- a design & process diagram of a solution
- a list of low hanging fruit that could be done in the near term towards the goal

**Comment by patricksimonian** [comment]
Problem Statement: 

As a community member, I find it challenging to contribute content to the Devhub. 
How can we streamline the contribution process so that I do not have to know the technical aspects to content contribution?

**Comment by jas29** [comment]
Problem Statement:
As an contributor, irrespective of the technical background, it is a hard and time consuming task to contribute to the devhub.
There should be an easier way for contributing to the devhub to save both effort and time for both the contributors and the maintainers

**Comment by patricksimonian** [comment]
Possible Personas:

1. A content contributor that is technically savvy and familiar with Github processes such as forking and pull requests

2. A content contributor that isn't familiar with Github and or does not have a technical background

**Comment by jas29** [comment]
Vision Statement:

Make contributing to debhub as easy as positing a post on facebook

**Comment by patricksimonian** [comment]
Vision Statement:

We imagine a process for getting content into the Devhub that is simple and doesn't require much or any knowledge of Github, JSON configuration files etc.

**Comment by patricksimonian** [comment]
Assumptions:

A user will have a Github Account

**Comment by patricksimonian** [comment]
Process Diagram: 
![content contribution pd](https://user-images.githubusercontent.com/21046727/73502045-93a08e00-437c-11ea-8ac8-d502ee9aea1d.png)

**Comment by patricksimonian** [comment]
Potential Solutions:

A) have a 'guided' tour  through contributing via a Github Issue Template and a 'Devhub Bot'
   pros: 
   - lots of work  done with this workflow in the `devops-requests`  repo (requestron)
   - least amount of effort
  cons:
  - validation will be challenging since github issues are 'free form'
  - 
      
B) have a front end form on the Devhub interface with an API to create PR's
   pros:
   - be  aesthatically pleasing
   - form validation is possible on the front end
   - doesn't  require a lot of technical know how (you'd still need a github account)
   cons:
   - requires more work as a front end interactive form needs to be built, as well as a backend

C) a combination  of A and B, the front end form  creates an issue on the Devhub which interacts with a bot.
   pros:
    - allows to leverage requestron to reduce  some work load
   cons:
   - there is a  duplication of efforts as you'd need two microservices,  a devhub api and a devhub bot

**Comment by kelpisland** [comment]
Great work guys - @sheaphillips and will chat and then we'll plan next steps.

**Comment by sheaphillips** [comment]
> Process Diagram:
> ![content contribution pd](https://user-images.githubusercontent.com/21046727/73502045-93a08e00-437c-11ea-8ac8-d502ee9aea1d.png)

If this were involving an interactive frontend, the validation step could provide a patch/PR creation step to provided fixes for malformed files.

An additional capability might be to provide for dropping in markdown content to a web form (instead of pointing to a repo).  This could then (via PR) get added into a content repo for the DevHub.

**Comment by patricksimonian** [comment]
totally agree. I had that thought in the back of my head as a future implementation.
