### ISSUE TITLE
Jenkins cleanup stage

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/devhub-app-web#1263]
**Is your feature request related to a problem? Please describe.**

The clean up stage for jenkins is not doing proper clean up.

**Describe the solution you'd like**

Delete the dev instance of jenkins and all other objects related, and webhook on repos.

**Describe alternatives you've considered**

Update BCDK?

**Additional context**

**Comment by patricksimonian** [comment]
hmm
i think this is a bug with the jenkins job. It redploys itself unfortunately so it will never get to that cleanup stage :( perhaps we should cleanup prior to redeploying in prod

**Comment by ShellyXueHan** [comment]
@patricksimonian @jas29 I'd like to raise your attention on this issue. Built images in `devhub-tools` have taken up 95GB registry space already! Please schedule some fix, sooner the better.

**Comment by patricksimonian** [comment]
closing as duplicate
