### ISSUE TITLE
Devhub Issue: BC Government API Guidelines [hyperlink render issue on devhub]

### ISSUE THREAD

**Issue by ll911** [bcgov/devhub-app-web#1266]
## Devhub Content Issue
> path: (do not delete) https://github.com/bcgov/api-guidelines/blob/master/government-of-british-columbia-api-guidelines.md
 > (do not delete) devhub page: mailto link on devhub page did render correctly, it renders correctly on github but incorrect on devhub
on devhub the hyperlink became `https://github.com/bcgov/api-guidelines/blob/master/mailto:jeff.card@gov.bc.ca`
it should be `mailto:jeff.card@gov.bc.ca`

**Comment by patricksimonian** [comment]
This is a bug with the `remark-path-transform-plugin` it looks like its erroneously transforming mail to links. We should verify that the URLs are relative prior to transforming. I will close this issue and reopen as a valid bug for the app :) Thanks!
