### ISSUE TITLE
Clicking "persona" pills doesn't show all resources associated with a given persona

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#1293]
**Describe the bug**
Clicking on persona "pill" on a standalone page *should* go to a page showing all resources associated with the clicked persona. 

**To Reproduce**
1. Go to a standalone page that has persona metadata. (e.g. https://developer.gov.bc.ca/Alignment)
2. In the "Resource Information" section at the top of the page, click on the pill labelled 'Developer'.  You will be taken to a search results page. 
3. The page will be as shown in attachment (a single resource shown).

**Expected behavior**
A set of search results including the many resources with "Developer" metadata persona value.

**Screenshots**
<img width="1215" alt="Screenshot 2020-02-27 16 49 28" src="https://user-images.githubusercontent.com/698658/75500485-ed977200-5981-11ea-9957-6ed4bf380d08.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari, Chrome
 - Version 13.0.5, 80.0.3987.122

**Additional context**
The example provided is for the "Developer" pill.  The Product Owner and Designer pills seem to show an empty list.

**Comment by patricksimonian** [comment]
hmm this was definitely missed when doing the algolia integration. I will look into how to get filters applied again. It should be easy enough!
