### ISSUE TITLE
Devhub unable to use searchgate because of CORS

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1301]
For some reason we are getting cors issue with search gate
<img width="1483" alt="Screen Shot 2020-03-04 at 3 04 36 PM" src="https://user-images.githubusercontent.com/21046727/75931342-8e29de00-5e29-11ea-8a02-408f53ec61d0.png">

**Comment by jas29** [comment]
cannot seem to re-produce this error. Did you see this in any specific environment or page ?
