### ISSUE TITLE
Show metadata (labels) in page header as clickable "pills"

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#1311]
**Is your feature request related to a problem? Please describe.**
Sometimes, it is useful to view content that is related via some metadata value, but that is not perhaps part of the same journey, topic, or for the same persona.  e.g. all content with a table "DevOps", where there is no "DevOps topic, journey, or persona.

**Describe the solution you'd like**
Display metadata labels attached to content in page header (same/similar to Persona, Topic, etc.) and provide for it to be clickable, upon which all pages with the same metadata value are shown in a search-result style view.

**Describe alternatives you've considered**
- creating topics for all permutations of metadata values

**Additional context**
- quite a bit of content will likely be related based on metadata values, but not necessarily based on Topic, so this would provide an alternate way of seeing logically related content.

**Comment by patricksimonian** [comment]
I like the idea. In my head i've thought of labels more as the key/value pair datastructure since it'd provided a richer way to display and gather information on pages. 

We currently support `tags` but that is primarily used for helping search as is the typical case in a lot apps.

Some example labels could be:
```yaml
---
labels:
  ministry: Citizens' Services
  theme: DevOps
```
what do you think?

**Comment by patricksimonian** [comment]
controlling these things are challenging, this is where having a metadata service to couple/watch github files and bind metadata to them would be useful 🤔
