### ISSUE TITLE
Images not showing up on cards in Home, or Topics view

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#1323]
**Describe the bug**
Images for resources that include them in front matter are not showing up on cards in Home, or Topics view, but they are in resource type views and search results.

**To Reproduce**
1. Go to devhub home page. 
2. Click on "topics" in top nav. 
3. Scroll down to "Collaboration Tools" topic.
4. Note there is no image showing for Rocket.Chat card.
5. Select "Topics" from top nav.
6. Find Rocket.Chat card and note there *is* an image showing.
7. Click "Home" in top nav
8. Search for "rocket"
9. Note image is also showing for Rocket.Chat card in search results.

**Expected behavior**
Cards should always include images for resources that have them specified.

**Screenshots**
<img width="698" alt="Screenshot 2020-03-20 15 55 14" src="https://user-images.githubusercontent.com/698658/77212334-f46a5e00-6ac3-11ea-8f44-c7eaa1f5537a.png">
<img width="1045" alt="Screenshot 2020-03-20 15 55 07" src="https://user-images.githubusercontent.com/698658/77212323-ef0d1380-6ac3-11ea-8906-e485c36a92a8.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 13.05.

**Additional context**
This is a worthwhile fix as fixing it will add some bling to the DevHub :)

**Comment by patricksimonian** [comment]
interesting. @jas29 lets bring this into the backlog for next sprint.
