### ISSUE TITLE
Ready OCP 101 for online delivery

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1332]
## Background

The ocp101 course is going to be delivered online and needs to be readied for that. 

## To Dos

- Convert slides into MIRO board
- Work on a way to deliver lectures online with examples using a virtual board

**Comment by ShellyXueHan** [comment]
tasks:
- push the base image
- get large quota in the namespace
- test out screen sharing + RC channel chat + responding to students during the course
- test out trouble shooting with individual students

**Comment by patricksimonian** [comment]
we were invited to the agile fundamentals course @ShellyXueHan i think this is a great opportunity to see how they do their online deliveries. We will learn a bunch :)
