### ISSUE TITLE
Create a Github user account for making pull requests via the devhub api

### ISSUE THREAD

**Issue by jas29** [bcgov/devhub-app-web#1382]
A Github service account is needed for the content contribution feature.

When a user suggests new content via the content contribution feature (form), a pull requested will be generated. In order to create a pull request, github credentials such as username and email are needed. Therefore, it is best to have a user account to solve this purpose.

This will later transition to a github app

**Comment by lukegonis** [comment]
@jas29 can you please give this issue a more descriptive title? Let myself or @patricksimonian know if you have any questions. Thanks!

**Comment by patricksimonian** [comment]
GOAL: deploy devhub to ARO
