### ISSUE TITLE
SG - OCP 3.11 - Requestron Updates

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#1479]
As a Platform Admin I would like to have an automated feature in Requestron bot that automatically closes devops-requests tickets in the case 
when a Platform Admin asked for additional info from the client that opened the request but no response is received from the client.

Add a label to the ticket when it gets closed for this reason e.g. no client response received.

Definition of Done: When the bot is capable of marking a ticket as stale appropriately, and then marking the ticket as closed if it remains stale for 2 weeks, then this ticket will be considered done.

**Comment by caggles** [comment]
@lukegonis should i close the epic now that everything is done, or leave it until the end of the sprint?
