### ISSUE TITLE
BCGov GitHub Org - 2FA enforcement

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/devhub-app-web#1501]
**Describe the issue**
2FA to be enforced for the BCGov GitHub org.  
This will enforce that owners and collaborators of BCGov repos have a heightened authentication level on their accounts.

Will require communication to BCGov org repo owners/collaborators.

**Which Sprint Priority is this issue related to?**
Technical debt

**Additional context**
**Preparing to require two-factor authentication in your organization**
Before requiring two-factor authentication (2FA), you can notify users about the upcoming change and verify who already uses 2FA.

We recommend that you notify organization members, outside collaborators, and billing managers at least one week before you require 2FA in your organization.

_When you require use of two-factor authentication for your organization, members, outside collaborators, and billing managers (including bot accounts) who do not use 2FA will be removed from the organization and lose access to its repositories. They will also lose access to their forks of the organization's private repositories._

Before requiring 2FA in your organization, we recommend that you:
- Enable 2FA on your personal account
- Ask the people in your organization to set up 2FA for their accounts
- See whether users in your organization have 2FA enabled
- Warn users that once 2FA is enabled, those without 2FA are automatically removed from the organization

https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/preparing-to-require-two-factor-authentication-in-your-organization

**Definition of done**
- [ ] Communication to users (RocketChat)
- [ ] Communication to users (email)
- [ ] wait 1 week from communication
- [ ] Enable 2FA enforcement in GitHub Org Settings (https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication)

**Comment by jefkel** [comment]
Could someone with permissions move this ticket from the devhub-app-web repository to the developer-experience repository?

**Comment by NickCorcoran** [comment]
Was easier to just close and recreate in correct repo.  https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/629
