### ISSUE TITLE
Keycloak High Availability Tuning

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1502]
As KC makes the transition to an enterprise service, it has required us to take a deeper look into how we operate KC. What is the best way to operate it?

This epic tracks our progress in configuring/tuning KC so that it more highly available, and has a known metrics/limitations to how it handles load, fail overs etc. In addition, we will be able to identify how KC tuning/upgrades impacts service delivery. 

Value Add:

- we will be able to understand well how KC operates on our platform, its limitations and behaviour under load. With this we can start to create an informed SLA.

**Comment by ShellyXueHan** [comment]
Update:
- major tasks identified here on miro: https://miro.com/app/board/o9J_khu92x4=/ create corresponding tickets
