### ISSUE TITLE
search not working?

### ISSUE THREAD

**Issue by ll911** [bcgov/devhub-app-web#1565]
**Describe the bug**
<img width="1194" alt="Screen Shot 2021-02-12 at 12 43 19 PM" src="https://user-images.githubusercontent.com/11949273/107820594-e6eb4180-6d2f-11eb-82c1-e63afa2462e4.png">

**To Reproduce**
see the screenshot

**Expected behavior**
return correct associated result 

**Screenshots**
attached 

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome, safari]
 - Version [latest]

**Comment by patricksimonian** [comment]
looks like the search index was not properly cloning.

**Comment by patricksimonian** [comment]
![Uploading Screen Shot 2021-02-22 at 3.24.27 PM.png…]()

**Comment by patricksimonian** [comment]
we're adding some tags to the artifactory doc so that it surfaces more easily.
