### ISSUE TITLE
Subscription Service should fetch public segments dynamically

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#1570]
## Summary

Currently a user can unsubscribe/subscribe to one configured form at a time in the mautic subscription app. It's imagine-able that platform services would have multiple segments that a user would potentially want to have access to. 

## To Do

- [x] Subscription app dynamically fetches the segments that are publicly available through the backend server

**Comment by AndrewJun97** [comment]
PR for backend groundwork tracked in https://github.com/bcgov/Mautic-Subscription-App/pull/26
