### ISSUE TITLE
[Pipeline Templates] Develop a Jenkins pipeline template to perform a SAST scan using SonarQube

### ISSUE THREAD

**Issue by michaelshire** [bcgov/devhub-app-web#1666]
DoD:
[ ] template has been reviewed by BC Gov
[ ] template has been tested and is working
[ ] template has been demoed to BC Gov platform services team during huddle
[ ] template is available to BC Gov community, in the appropriate repo folder

**Comment by Nicole-Huard** [comment]
@mitovskaol based on yesterday's call about priorities, should this issue (and the others related to Jenkins) be closed or will you keep them in the backlog?
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/devhub-app-web/1667 
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/devhub-app-web/1668
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/devhub-app-web/1669
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/devhub-app-web/1670

**Comment by mitovskaol** [comment]
@Nicole-Huard I will close them
