### ISSUE TITLE
[Pipeline Templates] Develop a Jenkins pipeline template to perform a DAST scan using OWASP-full

### ISSUE THREAD

**Issue by michaelshire** [bcgov/devhub-app-web#1667]
DoD:
[ ] template has been reviewed by BC Gov
[ ] template has been tested and is working
[ ] template has been demoed to BC Gov platform services team during huddle
[ ] template is available to BC Gov community, in the appropriate repo folder

**Comment by mitovskaol** [comment]
The decision was made to discourage teams on the Platform from using Jenkins and migrate to other automation tech. Therefore, we won't be investing effort into developing the templates for Jenkins pipelines.
