### ISSUE TITLE
[Pipeline Templates] Develop a Tekton pipeline template to perform a SAST scan using SonarCloud

### ISSUE THREAD

**Issue by michaelshire** [bcgov/devhub-app-web#1671]
DoD:
[ ] template has been reviewed by BC Gov
[ ] template has been tested and is working
[ ] template has been demoed to BC Gov community during Meetup
[ ] template is available to BC Gov community, in the appropriate repo folder

**Comment by gregnrobinson** [comment]
Can be added to **In Review**

https://github.com/bcgov/security-pipeline-templates/releases/tag/v0.2.1

https://github.com/bcgov/security-pipeline-templates/pull/12

**Comment by Nicole-Huard** [comment]
DoD updated to reflect the change from "demo at Team Huddle" to "demo at Community Meetup" - scheduled for December 14

**Comment by Nicole-Huard** [comment]
Reviews complete; presented at Meetup Jan 4th; Olena confirmed we can move on to the recordings
