### ISSUE TITLE
[Pipeline Templates] Develop a Tekton pipeline template to perform a SAST scan using SonarQube

### ISSUE THREAD

**Issue by michaelshire** [bcgov/devhub-app-web#1672]
DoD:
[ ] template has been reviewed by BC Gov
[ ] template has been tested and is working
[ ] template has been demoed to BC Gov community during Meetup
[ ] template is available to BC Gov community, in the appropriate repo folder

**Comment by gregnrobinson** [comment]
Can be added to **In Review**

https://github.com/bcgov/security-pipeline-templates/releases/tag/v0.2.1

**Comment by Nicole-Huard** [comment]
Ready for review & testing!
https://github.com/bcgov/security-pipeline-templates/blob/main/tekton/README.md

**Comment by Nicole-Huard** [comment]
DoD updated to reflect the change from demo at Team Huddle to demo at Community Meetup (December 14)

**Comment by Nicole-Huard** [comment]
Reviews complete; presented at Meetup Jan 4th; Olena confirmed we can move on to the recordings
