### ISSUE TITLE
[Pipeline Templates] Develop a Tekton pipeline template to perform a DAST scan using OWASP-baseline

### ISSUE THREAD

**Issue by michaelshire** [bcgov/devhub-app-web#1674]
DoD:
[ ] template has been reviewed by BC Gov
[ ] template has been tested and is working
[ ] template has been demoed to BC Gov community during Meetup
[ ] template is available to BC Gov community, in the appropriate repo folder

**Comment by Nicole-Huard** [comment]
@gregnrobinson check out the open source OWASP zap scanner

**Comment by gregnrobinson** [comment]
Created Template and added to release [v0.2.0](https://github.com/bcgov/security-pipeline-templates/releases/tag/v0.2.0)

https://github.com/bcgov/security-pipeline-templates/pull/11

**Comment by gregnrobinson** [comment]
Can be moved to **In Review**.

**Comment by Nicole-Huard** [comment]
Ready for review & testing!
https://github.com/bcgov/security-pipeline-templates/blob/main/tekton/README.md

**Comment by Nicole-Huard** [comment]
DoD updated to reflect the change from "demo at Team Huddle" to "demo at Community Meetup" - scheduled for December 14

**Comment by Nicole-Huard** [comment]
Reviews complete; presented at Meetup Jan 4th; Olena confirmed we can move on to the recordings
