### ISSUE TITLE
[Pipeline Templates] Develop a Tekton pipeline template to perform a Container scan using Trivy

### ISSUE THREAD

**Issue by michaelshire** [bcgov/devhub-app-web#1675]
DoD:
- [x] template has been reviewed by BC Gov
- [x] template has been tested and is working
- [x] template has been demoed to BC Gov community at Meetup
- [x] template is available to BC Gov community, in the appropriate repo folder

**Comment by Nicole-Huard** [comment]
Ready for review & testing!
https://github.com/bcgov/security-pipeline-templates/blob/main/tekton/README.md

**Comment by Nicole-Huard** [comment]
DoD updated to reflect the change from "demo at Team Huddle" to "demo at Community Meetup" - scheduled for December 14

**Comment by Nicole-Huard** [comment]
Reviews complete; presented at Meetup Jan 4th; Olena confirmed we can move on to the recordings
