### ISSUE TITLE
Install AppAssessment into GOLD and GOLDDR Clusters

### ISSUE THREAD

**Issue by Nicole-Huard** [bcgov/devhub-app-web#1689]
We want to make the appAssessment services available to the Gold customers as well as to Silver teams.

DoD:
- [ ] the appAssessment service is available to the teams developing in the Gold Hosting Tier

**Comment by ShovelHand** [comment]
Since AppAssessment is now installed via the command line with a reference to the imagestream, I believe this issue is resolved.
