### ISSUE TITLE
Broken link on https://developer.gov.bc.ca/topic/featured/Documize

### ISSUE THREAD

**Issue by cnburnett** [bcgov/devhub-app-web#1701]
**Describe the bug**
Broken link on https://developer.gov.bc.ca/topic/featured/Documize

**To Reproduce**
1. Go to https://developer.gov.bc.ca/topic/featured/Documize
2. Scroll down to link = 'https://docs.pathfinder.gov.bc.ca/'
4. See error "This site can’t be reached"

**Expected behavior**
Was hoping to see more info on a local (BC Gov) install of Documize

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome

**Interested because**
I am developing docs for the new BC Bid. Had looked into docs in repo like Hugo/Docsy. Going with CMS Lite for now. How can I get in touch with the folks trying out Documize in BC Gov?

**Comment by mitovskaol** [comment]
@cnburnett Please feel free to reach out to me in MS Teams. We created our own Documize instance to have a protected space for some of our docs that are too sensitive for the public space. Most of ours docs live in GitHub but some that require authentication for access (GitHub ID or IDIR) have been moved to Documize. We are, however, looking to migrate all content into WordPress and when this happens, will retire Documize.
