### ISSUE TITLE
2 Rocketchat accounts

### ISSUE THREAD

**Issue by Amitisp** [bcgov/devhub-app-web#1734]
Hello, 

I have 2 accounts in Rocketchat and I only need the one that is linked with email [amitis.partovi@freshworks.club] - All my previous messages and texts are with the mentioned account.

However, I am stuck in the account that is linked to [amitis.partovi@gov.bc.ca] which I do not use and I cannot get out of it. 

Please help.

**Comment by Amitisp** [comment]
@ShellyXueHan can someone please assist me with this issue?

**Comment by ShellyXueHan** [comment]
hello @Amitisp what type of account did you use to login? github or IDIR?

**Comment by ShellyXueHan** [comment]
FYI, https://github.com/BCDevOps/devops-requests would be a better place to get someone to help you on access stuff! Are you still able to login to RC at the moment? If so, pls poke me on Rocketchat and we'll get it figure out!

**Comment by Amitisp** [comment]
@ShellyXueHan 

> hello @Amitisp what type of account did you use to login? github or IDIR?

I can't remember

**Comment by Amitisp** [comment]
@ShellyXueHan I need the account with username @apartovi to be deleted 
I should only have the @amitis.partovi account.

**Comment by Amitisp** [comment]
@ShellyXueHan if you are messaging me on RC, I am not seeing them.

**Comment by Amitisp** [comment]
Continuing our conversation from RC here. I logged out to show you what I got when I tried to get into RC via GitHub, but miraculously it let me in and I am back on my original RC account @amitis.partovi!

**Comment by Amitisp** [comment]
Can you please delete the RC account @apartovi so there isn't 2 of me in there which confuses people.
Thanks!

**Comment by ShellyXueHan** [comment]
okay! Your rocketchat account from IDIR has been deleted! pls reopen this ticket if issue persist.
