### ISSUE TITLE
Devhub Issue: User access into Github or Openshift [short description here]

### ISSUE THREAD

**Issue by brad-sparks-gov-bc-ca** [bcgov/devhub-app-web#1775]
> path: (do not delete) https://github.com/bcgov/devhub-app-web/blob/master/web/src/assets/migrated-pages/Getting-Started-on-the-DevOps-Platform/UserAccessToOrg.md
 > (do not delete) devhub page: /User-access-into-Github-or-Openshift

**Comment by ty2k** [comment]
Hey @brad-sparks-gov-bc-ca, if you are looking for up to date info on GitHub organizations used by the BC Gov, please see our new documentation site: [BC Government organizations in GitHub](https://beta-docs.developer.gov.bc.ca/bc-government-organizations-in-github/)

The content from the DevHub page that was [here](https://developer.gov.bc.ca/User-access-into-Github-or-Openshift) can be found in its source repository, but note that it is out of date and the repository will be retired soon: https://github.com/BCDevOps/developer-experience/blob/master/docs/UserAccessToOrg.md
