### ISSUE TITLE
Devhub Issue: Getting human support for issues not covered by devops-requests [restore deleted repo]

### ISSUE THREAD

**Issue by dstainton** [bcgov/devhub-app-web#1789]
> path: (do not delete) https://github.com/bcgov/devhub-app-web/blob/master/web/src/assets/migrated-pages/Getting-Started-on-the-DevOps-Platform/HumanHelp.md
 > (do not delete) devhub page: /Getting-human-support-for-issues-not-covered-by-devops-requests

## Devhub Content Issue
Last week I was doing some cleanup on my github forks and inadvertently deleted the 'bcgov/ols-geocoder-cpf-plugin' repo instead of my fork. Could that repo be restored, please?

**Comment by ty2k** [comment]
Closed #1791
