### ISSUE TITLE
Devhub Issue: Getting human support for issues not covered by devops-requests [restore deleted repo]

### ISSUE THREAD

**Issue by dstainton** [bcgov/devhub-app-web#1791]
> path: (do not delete) https://github.com/bcgov/devhub-app-web/blob/master/web/src/assets/migrated-pages/Getting-Started-on-the-DevOps-Platform/HumanHelp.md
 > (do not delete) devhub page: /Getting-human-support-for-issues-not-covered-by-devops-requests

## Devhub Content Issue
A bit more than a week ago, I inadvertently deleted a GitHub repo instead of my fork of said repo. I sent a request via email to have it restored, and created a ticket last week to do the same. I've not had a response, so I suspect I'm doing something wrong (I'm new here). The repo is bcgov/ols-geocoder-cpf-plugin. If it could be restored, please, or someone can contact me about it at drew.stainton@gov.bc.ca, I would appreciate it. Thanks.

**Comment by ty2k** [comment]
Hey @dstainton , I see the [bcgov/ols-geocoder-cpf-plugin](https://github.com/bcgov/ols-geocoder-cpf-plugin) repository has been restored, so you should be good to go.
