### ISSUE TITLE
Devhub Issue: Need more quota for OpenShift project set? Resource Quotas for bf5ef6 project set in gold cluster

### ISSUE THREAD

**Issue by rstens** [bcgov/devhub-app-web#1795]
> path: (do not delete) https://github.com/bcgov/devhub-app-web/blob/master/web/src/assets/migrated-pages/Developer-Tools/request-for-quota-increase.md
 > (do not delete) devhub page: /Need-more-quota-for-OpenShift-project-set

## Devhub Content Issue
The current quota does not allow me to have my application started.
My application needs:

- N8N
- Redis
- PostgreSQL
- Adequate storage

I would characterize my application as a medium to large, as the basic installation is just the start.
I did spend half a day trying to whittle down the resource usage, but my application will simply not even start up.

This is for The Platform Post Upgrade Test Automation.

Thanks,

Roland Stens

**Comment by MonicaG** [comment]
Hi @rstens 

Please see the [Request a quota increase for an OpenShift project set](https://docs.developer.gov.bc.ca/request-quota-increase-for-openshift-project-set/) for details on how to do this. Or contact the platform services team at: [PlatformServicesTeam@gov.bc.ca](mailto:PlatformServicesTeam@gov.bc.ca).

This request cannot be done via an issue in this repository.

**Comment by rstens** [comment]
I am aware of the process, due to other problems I was unable to it myself, but it is being worked on.
BTW the link for this issue creation comes from the registry application, so either that is wrong or it is an escalation mechanism.
Anyway, all good.

**Comment by MonicaG** [comment]
Hi @rstens 

Would you please provide a link to the registry application. I'll investigate to see why it is posting an issue here.

Thank you,

Monica

**Comment by rstens** [comment]
https://developer.gov.bc.ca/Need-more-quota-for-OpenShift-project-set

So actually not in the registry application but in a page that was referenced from there and seemed to be relevant.
My bad.
