### ISSUE TITLE
As a signing system user, I would like error messages propagated back to the web so I can see why jobs fail

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#201]

**Comment by rajpersram** [comment]
Attached is a mockup of 3 different levels of messaging: confirmation, warning and error. Each would display at the top under the title but above the content. Messages could fade out after 5 seconds or we could implement the need to manually close the message box.

![4-Error-Messages-100756059-1546630903.png](https://images.zenhubusercontent.com/5c2e4cfdab4f3464fb8df8d1/53e99a81-1432-4970-b8d9-9435c22055e6)

**Comment by rajpersram** [comment]
Live mockup link: https://goo.gl/96PwDB

**Comment by jleach** [comment]
@lukegonis This features is done. Go ahead and close it out.
