### ISSUE TITLE
Devhub Branding is not inline with Gov Standards

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#216]
## What's wrong
Devhub Logo as it is at https://developer.gov.bc.ca is not inline with gov standards.

## What I'd expect
The border should be removed and the font color should be white.

**Comment by patricksimonian** [comment]
@luke @orinevares This seems like a good issue for either of you to kick off.

**Comment by ksingbeil** [comment]
@patricksimonian Thanks for adding this issue!
