### ISSUE TITLE
As a user I'd like a search bar to filter content

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#225]
**Is your feature request related to a problem? Please describe.**
#224 integrated lunr but no ui changes exist yet

**Comment by patricksimonian** [comment]
How do we want the user experience of the search bar to work? The index is actually quite large so some preliminery testing with a search 'on key stroke' had the slightest lag to it. I think this could be optimized but perhaps there is a better solution for search?

**Comment by rajpersram** [comment]
Attached below is the most recent (s7) version of the sidebar search wireframe.

[https://app.zenhub.com/files/148679594/ea8f04fc-60f6-4a51-9947-39e76ca3cec7/download](https://app.zenhub.com/files/148679594/ea8f04fc-60f6-4a51-9947-39e76ca3cec7/download)
