### ISSUE TITLE
Card action buttons could use tooltips on hover to describe "what they do"

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#245]
It would help usability to have hoverable tool tips for each of the action buttons on the cards so it's clear to users what will happen when they click one.

**Comment by dlevineBC** [comment]
Could you provide an example of what these action buttons are? Is it going to the full page of the card?

**Comment by sheaphillips** [comment]
action buttons are the little icons at the bottom of some of the cards -
the speech bubble (comment), octocat (repo link), etc. We will implement
new/different ones as we go. See screenshot.

[image: Screenshot 2019-01-18 14.35.24.png]

**Comment by dlevineBC** [comment]
Thanks, I would recommend providing the label of the what the action is next to the icon, rather than a hover tooltip. You should (almost) never rely on an icon alone unless it's an extremely well known icon like "save" or "close"

**Comment by patricksimonian** [comment]
this issue is being dropped as the card ui has changed. there are no 'action buttons' to have tooltips for.
