### ISSUE TITLE
Display URL of PR-triggered deployment in github pull request

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#292]
With PR triggered builds, a deployment happens on successful build.  We can click through to Jenkins to see the build progress, etc. It would be nice to also be able to click through to the deployed app once it has deployed successfully. This probably means a callback to the Github from the pipeline to add this info once it is avaialble.

**Comment by lukegonis** [comment]
@patricksimonian this issue is pretty old, do you think it is still relevant?

**Comment by patricksimonian** [comment]
closing as this is stale
