### ISSUE TITLE
Missing personas value causes source/resource to be ignored.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#300]
**Describe the bug**

Sources or resources that end up not having a value for persona do not show up in the ui.

**To Reproduce**

Steps to reproduce the behaviour:
1. Create a collection or source and don't provide a value for personas at any level in the registry, or in resources themselves.
2. npm run dev
3. Notice that the resources that should come from the new collection + source don't show up.

**Expected behaviour**

Resources should show up even they don't have a persona. Perhaps the default should be 'all' or equivalent.

**Comment by patricksimonian** [comment]
this issue has been resolved.
