### ISSUE TITLE
create beta sticker

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#312]

**Comment by patricksimonian** [comment]
@dlevineBC do you have any ideas on what it should look like>?

**Comment by lukegonis** [comment]
@patricksimonian @dlevineBC John Jordan's team (two doors down the hall from DevHub) just launched OrgBook, they have a 'Public Beta' sticker in their headers, might be something we want to reuse
https://orgbook.gov.bc.ca/en/home

**Comment by dlevineBC** [comment]
@lukegonis @patricksimonian We've started an issue on the design system to explore all the option. We've got that one captured https://github.com/bcgov/design-system/issues/78
