### ISSUE TITLE
Should we open external links in a new tab and/or allow do this selectively at the resource level?

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#324]
Clicking on some cards (external links in particular) should maybe open in a new tab.  We probably should have a default for this, and allow override. e.g. `sourceType: web` => defaults to new tab, but can be overridden in the source definition within the registry.

**Comment by patricksimonian** [comment]
Perhaps @dlevineBC and @orinevares can provide some input on this. My questions would be, when a link is external, do we present it in a different way to differentiate between internal navigation? Secondly if we do want to present them differently, are there any differences between an external link that goes to a new tab/ new browser as far as presentation is concerned?

**Comment by dlevineBC** [comment]
@patricksimonian 
For external links, it's good to present an indicator icon that it's taking you outside of the site. When we get the font-awesome stuff together we can identify the icon for that.

Links should never open in a new tab or window

**Comment by patricksimonian** [comment]
closing this issue as its resolved #496 will attend to this inconsistency
