### ISSUE TITLE
Support for different sources for Card "author" avatars - gravatar, raw image, etc. as well as github

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#326]
Currently we intepret the author field as a github username.  we should support other alternative sources as well since GitHub user isn't always going to capture the intent we have with `author`.  Other sources might do a better job and provide more flixeibility.

**Comment by patricksimonian** [comment]
I think this would be a neat package. It could establish a convention more or less for retrieving an avatar based on a label. 

Thoughts on implementation? 

I'm thinking

```js
const imagePath = avatarMe('github:patricksimonian'); // => 'https://github.com/patricksimonian.png'
```

**Comment by sheaphillips** [comment]
Yup that’s what I was thinking too.

**Comment by patricksimonian** [comment]
this component has been built, found in src/components/ui/Avatar
