### ISSUE TITLE
Support inline markdown and markdown files for collection overview

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#334]
Currently we allow text to be provided in the registry collection definition that is displayed beneath the collection title.  For this content, we should support inline markdown as well as external markdown files so that rich content / formatting can be used to add visual interest.

**Comment by patricksimonian** [comment]
@sheaphillips so we do support external markdown files as a collection over page currently. This plus the ongoing work on the 'graph data structure' changes may circumvent the need for inline markdown. What do you think?

**Comment by sheaphillips** [comment]
by collection overview, I meant the blurb the descriptive text that
displays along with the collection title (collection.description I think?),
not a custom collection template.  It's lowish priority but it would be
cool if we this could be markdown or markdown file reference, so we can get
rich text in there.  Did I miss something?

**Comment by patricksimonian** [comment]
ohh i see, big misunderstanding. yes you mean the `collection.description` property. So to be clear we'd want to support referencing markdown files to source that content or have some inline configuration. 

I see the latter as the best option for now what do you think?

**Comment by sheaphillips** [comment]
yes, the latter would be fine...actually, if it was a function then we
could do whatever we want... :)

eg.:
...
decription: function:' markdownFile('https://github.com/blah.md')
