### ISSUE TITLE
Have someone review typical terms of use, etc. for vendor/external brand/product graphics so we know how we can use these within the Devhub.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#341]
For card graphics, we currently are making use of some external brand logos/graphics. (e.g. Slack).  Many of these logos (there could ultimately be dozens) will have their own copyright/trademarks/terms of use/legal goo that governs how they can be used.  We should task a qualified person with developing a standard guidance for us on this.

**Comment by kelpisland** [comment]
Good advice here:
https://www.upcounsel.com/permission-to-use-logo

**Comment by kelpisland** [comment]
All third party trademarks (including logos and icons) referenced by developer.gov.bc.ca remain the property of their respective owners. Unless specifically identified as such, developer.gov.bc.ca use of third party trademarks does not indicate any relationship, sponsorship, or endorsement between The Province of British Columbia and the owners of these trademarks. All references by developer.gov.bc.ca to third party trademarks are to identify the corresponding third party goods and/or services and intended to constitute nominative fair use under applicable trademark laws.
