### ISSUE TITLE
Experiment with TypeScript

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#343]
TypeScript could improve the quality, readability, and maintainability of our codebase.  We'd like to make use of it in one or more features and see how the promise holds up.

This task is just a placeholder for a brief tech spike activity to determine how/where to apply.

**Comment by patricksimonian** [comment]
@sheaphillips i've had thoughts of integrating typescript from the get go with the datastructure/devhub v3

shall we close this issue?

**Comment by sheaphillips** [comment]
sure - not really an issue anyway - more like a consideration.

**Comment by patricksimonian** [comment]
it's definitely something i'm interested in integrating. Jason did it for some of his work, it does end up making more concise code

**Comment by patricksimonian** [comment]
closing as this is a non-issue :)
