### ISSUE TITLE
Ability to share/reuse source definitions in registry across collections.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#357]
We have cases where we want a given source (most commonly sourceType web ) across multiple collections.  At the moment, the source definition needs to be duplicated for each collection.  It would be better to "normalize" this and allow the source to defined once and "Referenced". eg:

----------
sources:
  - name: 'OpenShift Overview'
  - sourceSlug: 'ocp-ovw'
  - sourceType: 'web'
...
collections:
- sources:
   - sourceRef: 'ocp-ovw'

**Comment by patricksimonian** [comment]
this sounds like a devhub v3 thing.

**Comment by sheaphillips** [comment]
what version are we on now? ;)

**Comment by patricksimonian** [comment]
I'm saying version 2 since the introduction of collections as a node type : D

**Comment by sheaphillips** [comment]
cool.
