### ISSUE TITLE
Update Footer with Design System requirements

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#369]

**Comment by dlevineBC** [comment]
We need to figure out a place to put the DevX logo and I think putting the logo down in the footer floating to the right would be a good spot. ![footer-logo.png](https://images.zenhubusercontent.com/5c34dbe032f2e5319a4339f8/9698cd97-a06d-4f2a-a840-b407c70f48f6)

**Comment by dlevineBC** [comment]
Logo file with white text
![new-logo-white.svg](https://images.zenhubusercontent.com/5c34dbe032f2e5319a4339f8/d0f6f460-ce73-4f37-91d0-97a0dff3177c)
