### ISSUE TITLE
Duplicate logo in header

### ISSUE THREAD

**Issue by jleach** [bcgov/devhub-app-web#372]
**Describe the bug**
When I go to the DevHub website I see duplicate logos in the header. Seems to be media query related as if I mouse over it goes away.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the website:
https://developer.gov.bc.ca/Open-Shift-Wiki/Postgres-Crash-Loop-Error-and-Solution
2. Look at the logo.

**Expected behaviour**

I should just see one logo.

**Screenshots**

[Video](https://www.dropbox.com/s/5zgrbohborb03x0/DebHubBug.mov?dl=0)

The flashes in the video are me reloading the page.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version Latest

**Comment by patricksimonian** [comment]
interesting i'll take a look into this
