### ISSUE TITLE
build-time GitHub API calls are getting rate limited, resulting in an error message in design system component previews

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#423]
![Screenshot 2019-02-21 15.22.17.png](https://images.zenhubusercontent.com/5717f666bf93871ccd99cae9/4ce9e029-5852-4384-b1d0-2352b4ff18a5)

We need to inject a Github credential/token when making the API calls to retrieve the sample content.  

This is in ComponentPreview.js.

**Comment by patricksimonian** [comment]
if we can verify that this is a build time process we should be able to inject via `process.env`

**Comment by sheaphillips** [comment]
I think the API call is being made at runtime as well/instead of build time...solution would be to do the work in a different react lifecycle method (build only) or somehow “save” the data at build time so the runtime call is a no-op.

**Comment by patricksimonian** [comment]
yeah that is something that I have been thinking about for a bit. Perhaps having remote file storage for all devhub 'funneled' assets?

**Comment by patricksimonian** [comment]
@sheaphillips looks like prod is missing a bunch of logos because of this. Can we attach local images for the time being?

**Comment by patricksimonian** [comment]
actually different issue

**Comment by sheaphillips** [comment]
Closing as this isn't a problem anyone other than we have reported. We may change the way at some point that we pull github content in (via a plugin) to eliminate it.
