### ISSUE TITLE
Design system title is missing

### ISSUE THREAD

**Issue by kparkerhall** [bcgov/devhub-app-web#440]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by patricksimonian** [comment]
We did some UI Changed recently that may have resolved this issue. Is there any way I can replicate this issue to check?

**Comment by kparkerhall** [comment]
Hi Patrick, it would be best to follow up with Todd as he was the one to noticed this.

Sorry I can’t be more help!

K

**Comment by patricksimonian** [comment]
No problem at all :) will do!

**Comment by patricksimonian** [comment]
closing issue as this does not appear to be a problem anymore. If there are any problems please open a new issue :)
