### ISSUE TITLE
font awesome version 5 upgrade

### ISSUE THREAD

**Issue by matthewhall78** [bcgov/devhub-app-web#454]
Broken Font Awesome icons

**To Reproduce**
1. Go to https://developer.gov.bc.ca/Design-System/Icons
2. icons are not displaying

**Expected behavior**
icons are showing

**Solution**
Font awesome has built a shim so you can fix them while you give yourself time to upgrade to v5 of font awesome.  https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4   

```
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/v4-shims.css">
</head>
<body>
  <!-- "close" is an alias to "times", V5 is <i class="fa fa-times"></i> -->
  <i class="fa fa-close"></i>

  <!-- Renamed to "image", V5 is <i class="fa fa-image"></i> -->
  <i class="fa fa-picture"></i>

  <!-- Needs the "fab" prefix, V5 <i class="fab fa-twitter"></i> -->
  <i class="fa fa-twitter"></i>

  <!-- "far" prefix, lose the "-o", V5 <i class="far fa-circle"></i> -->
  <i class="fa fa-circle-o"></i>
</body>  

```

**Comment by patricksimonian** [comment]
Thanks for the issue @matthewhall78 ! We are going to move this issue over to this design system. I'll link the the issue number shortly.

**Comment by patricksimonian** [comment]
Issue https://github.com/bcgov/design-system/issues/161
