### ISSUE TITLE
More contrast in colour selection used to denote "types".

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#464]
The current set of type-related colours includes a non-descript "dark grey" and two similar shades of blue, plus purple.  It would be nice to come up with something more visually distinct and appealing (esp. than grey).

**Comment by dlevineBC** [comment]
The icon and text are the primary information pieces, these colours were chosen to align with the BC DevExchange branding. The purple is the github branding. The gray could be changed, do you have a suggestion for collections?

**Comment by sheaphillips** [comment]
orange from the DevEx branding?

**Comment by dlevineBC** [comment]
The orange was going to be used for the Contacts once that's built. Maybe a less intense grey could work

**Comment by sheaphillips** [comment]
gonna run out of colours...

**Comment by patricksimonian** [comment]
I believe is a non issue any more.
