### ISSUE TITLE
Slack/Rocket.Chat integration with pipeline.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#467]
Currently, we have no easy way of tracking PR build/deployment progress other than monitoring Jenkins...or just waiting.  We should tie into Rocket.Chat to provide updates on this, along with the deployment URL as mentioned in another ticket.

**Comment by patricksimonian** [comment]
please see devhub-scheduled job. we have a rocket chat integration for that job :)
