### ISSUE TITLE
Clean up old builds/deployments.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#468]
we have old deployments/routes/builds etc. lying around. we should clean these up.

**Comment by patricksimonian** [comment]
I think i cleaned most of this up yesterday. I made a little tool to indentify stale PR's within our instance of the OCP-CD/CI pipeline and piped those results into a cleanup script Clecio came up with : -)

**Comment by patricksimonian** [comment]
I'll bundle that package into a release so that its usable

**Comment by patricksimonian** [comment]
i forgot to bundle it

**Comment by patricksimonian** [comment]
I did clean the old prs, but we are going to have some more for this sprint

**Comment by sheaphillips** [comment]
can we extend the jenkinsfile/pipeline logic to remove these artifacts?

**Comment by patricksimonian** [comment]
we definitely can and should. I'm thinking:
1. bundle up my stale pr checker tool
2. leverage it and the cleanup script to clear stale prs in the pipeline.
