### ISSUE TITLE
CSI Lab Page in the Enabler Collection

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/devhub-app-web#475]
https://devhub-static-dev-458-devhub-dev.pathfinder.gov.bc.ca/collections

May we please work towards listing the CSI Lab as an enabler?

The DevExchange created a page for us... and we do expect to update this with information about how to participate in the Lab.

https://www.bcdevexchange.org/csilab/

**Comment by patricksimonian** [comment]
Absolutely,

The basic info we need to add the card to the collection is: 
title:
short description (try to be under 140 characters):
a path to an image (ideally this image should be sourced from github or another reliable source to prevent a future broken link):
