### ISSUE TITLE
As a developer I would like to know which pull request is in test or prod environments

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#497]
It'd be great to be able to discern which PR is in test/prod based on a issue label or soomething. 

Perhaps we can include this into our jenkins file?

@sheaphillips thoughts on this? I don't see this as a ton of effort. We could work with the github API to create/assign a label with something like 'status:in-test' or 'status:in-prod' during the appropriate jenkins stage.

most likely involves authoring a node package

It would be great for a comment to be made against a pr with the url of the apps deployment

**Comment by sheaphillips** [comment]
The github “Deployments API” is probably the thing to explore. I think clecio has investigated.

**Comment by patricksimonian** [comment]
@cvarjao

**Comment by patricksimonian** [comment]
Is that what the chat ops bot was leveraging? Do we want to go down the route of developing a chat bot for deploying?

**Comment by patricksimonian** [comment]
Clecio may have done some work on this of which I do not want to duplicate, just waiting on a response from him.
