### ISSUE TITLE
Make page title match nav title

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#512]
![Screen Shot 2019-03-28 at 8.32.30 AM.png](https://images.zenhubusercontent.com/5c2e50794feb4829c0135179/bac34aa3-afa6-41ed-a115-e4f49662874f)

## Taking a look at the above screen shot..

There is an inconsistency with the Page Title __Prototype with the Design System__ and its cooresponding link __Prototyping Tools__ (found near the bottom left). 

This is because markdown files can be assigned a title that doesn't reflect the markdown title (this is because we cannot guarantee content contributors placing the correct headings on their markdown files). 

We should add the 'navigation title' which is actually the card title to the resource page. Keep in mind that __there are situations where a duplicate title would exist__. Navigation titles don't necessarily have to be set from the ___frontmatter title___ property. If a markdown file has a h1/h2 it can be used as the title automatically. 

This should influence the design somewhat as perhaps the 'card/navigation' title shouldn't be the most present thing on the page. 

@dlevineBC @sheaphillips @orinevares thoughts?

**Comment by orinevares** [comment]
Yes, if you click prototyping tools the title should read prototyping tools which provides assurance to the user that they are on the correct page. This is an issue that has come up in usability testing. The titles of some cards and collections don't match what people are expecting to find. It might be good to investigate how content ends up on DevHub to ensure proper naming and also clearly define as a group what each resource type includes. Once users become familiar with the ability to PR content and contribute this can also be crowdsourced and corrected that way.

**Comment by patricksimonian** [comment]
I think for now we should take the naive approach and modify all files that causing this issue.

**Comment by patricksimonian** [comment]
blocked by prs waiting to be submitted

https://github.com/BCDevOps/openshift-wiki/pulls #'s 25, 26, 27
https://github.com/bcgov/mobile-starter-kit/pulls #'s 5, 6

**Comment by patricksimonian** [comment]
@sheaphillips do you mind taking a breeze through those prs from above?
