### ISSUE TITLE
As a user I would like a consistent and clear experience/flow when exploring self-service tools in the DevHub so that I can understand their applicability, and access and usage models, among other things. 

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#513]
Inside Self Service Tools, many of the cards jump the user off to an external link with no clear context. The initial UI of the tool may no do a good job of explaining how/when the tool should be used, constraints, best practice, support model, etc.

It would be great to have a standard content 'package'  available in the DevHub for each self-service tool. This would include items such as:
- About Page
- How To Use
- Who Should Use
- How to access
- How to get help
- etc.

This is similar/related to the idea of a "Service Definition" such as the one produced for OpenShift [here](https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/OpenShift-Container-Platform-Service-Definition). The next "package" should be for the KeyCloak tool.

This should perhaps be a distinct template/page type that could render the content items above in a user-friendly "canvas" format such as the one [here](https://app.zenhub.com/files/148679594/532df2a7-f618-4b04-ae78-6d12336c9b23/download) (except in English instead of German).

**Comment by lukegonis** [comment]
Need an updated DOD for this @patricksimonian @sheaphillips
