### ISSUE TITLE
As a DevHub product owner, I would like an efficient review process for content contributions so that valid content can be  added to the DevHub as quickly as possible, while maintaining the curation ability.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#525]
Currently, we manage content contributions via pull requests in the same manner that we manage code changes.  We want to brainstorm/experiment other approaches that may be simpler and faster.

**Comment by patricksimonian** [comment]
We have gone with the approach of automating as much as we can. Things like metadata is now automated and validated via github actions. I'm closing this issue for now as I don't see much else work to do until content contribution becomes more of a priority.
