### ISSUE TITLE
Adjustments to homepage of DevHub. Title, intro, and How DevHub Works link.

### ISSUE THREAD

**Issue by orinevares** [bcgov/devhub-app-web#536]
![Screen Shot 2019-04-02 at 3.51.04 PM.png](https://images.zenhubusercontent.com/5c3d1a9054281239e265f387/fb5d663f-4de6-4355-9e4b-1b06a42577e1)

**Comment by patricksimonian** [comment]
PR has been rebased as up to now and is ready for merge.
