### ISSUE TITLE
BUG: embedded long png not showing correctly

### ISSUE THREAD

**Issue by ll911** [bcgov/devhub-app-web#542]
**Describe the bug**
embedded long png not showing correctly

**To Reproduce**
working => `https://github.com/BCDevOps/openshift-wiki/blob/master/docs/API/KongAPI.md#tldr---see-workflow-diagram-below`

not working => `https://developer.gov.bc.ca/Developer-Tools/API-Gateway-(powered-by-Kong-CE)#tldr---see-workflow-diagram-below`

**Expected behavior**
the image is not showing

**Desktop (please complete the following information):**
 - OS: [mac]
 - Browser [chrome, safari]
 - Version [latest]

**Comment by patricksimonian** [comment]
Looks like the image in the [markdown file](https://github.com/BCDevOps/openshift-wiki/blob/master/docs/API/KongAPI.md#tldr---see-workflow-diagram-below) is referenced like
```md
![](https://github.com/nokia/kong-oidc/blob/master/docs/kong_oidc_flow.png)
```

try changing it to this

```md
![](https://github.com/nokia/kong-oidc/blob/master/docs/kong_oidc_flow.png?raw=true)
```

### ?raw=true

Images sources from github by external origins must pass this property to get the image correctly

### Moving forward

This does bring up a good point where the devhub should be able to handle this situation automatically for github image uris. So i will make an issue for that and link it here.

**Comment by patricksimonian** [comment]
#543
