### ISSUE TITLE
Rename Collections to 'Topics'

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#560]
The devhub homepage and collections page should all be renamed to 'Topics'.

@orinevares do you mind attaching some mockups to this issue of what that is supposed to look like?

**Comment by orinevares** [comment]
@patricksimonian sure, they are subject to change after our design critique but here is where they are at now.

**Comment by orinevares** [comment]
<img width="687" alt="Screen Shot 2019-04-11 at 11 53 44 AM" src="https://user-images.githubusercontent.com/43620986/55983688-7c0ee200-5c50-11e9-8e37-255490db1abb.png">
