### ISSUE TITLE
Implement a carousel of cards within the topic containers

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#562]
this is based off of @orinevares designs. Pending some user feedback/testing. This design will be implemented. 

@orinevares do you mind plugging in those designs into this issue as reference.

**Comment by orinevares** [comment]
<img width="1085" alt="Screen Shot 2019-04-11 at 11 54 24 AM" src="https://user-images.githubusercontent.com/43620986/55983721-99dc4700-5c50-11e9-92ae-179653861db2.png">

**Comment by orinevares** [comment]
^ pending changes from our design critique

**Comment by patricksimonian** [comment]
@lukegonis hit a speed bump with carousels on mobile devices. They don't look so great. We should re-look at a layout for small view ports before continuing

**Comment by patricksimonian** [comment]
speedbump addresses
