### ISSUE TITLE
Create a card for what is pathfinder

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#567]
We should have a document hosted (on the devhub content repo) for explaining what Pathfinder is, its story etc.

**Comment by patricksimonian** [comment]
add a link back to a new route to pathfinder called pathfinder.deprecated.gov.bc.ca

**Comment by patricksimonian** [comment]
@kelpisland a doc is ready to go for editing :) https://github.com/bcgov/devhub-resources/edit/master/resources/pathfinder/what-is-pathfinder.md

**Comment by patricksimonian** [comment]
I left the description property at the top blank. This should be a short description (under 140 charactersish) introducing the card

**Comment by lukegonis** [comment]
dump in content from pathfinder
-if you want to get fancy you can add mobile, devops and blockchain
