### ISSUE TITLE
Add a card explaining how devhub works

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#572]
WE should have a card which explains devhub as a site,  how to use it.

Explanation of abstraction point (resources, resourcetypes and topics).

Eventually this will include content contribution contens.

**Comment by patricksimonian** [comment]
## Welcome to Devhub

  

A place to learn, discover and collaborate on digital products within the BC Government.

  

### Who should use this application?

  

This application is geared towards Developers working on digital products within Gov (with a focus on Agile Development), however there is useful information for anyone interested in BC Gov digital landscape.

  

### What is the Devhub and How does it work?

  

The Devhub is content aggregator application. It leverages modern tooling/frameworks to source content across different types of media. This media can be from a markdown file within a Github Repository, a link to a website, events from 3rd party providers and more. We are working towards expanding the types of media Devhub supports to make it immersive, and useful in your workflow.

  

Whenever the Devhub is refreshed in production (the live public facing website), it seeks out all the content that it is subscribed too and pulls it into the application.

  

### What is problem Devhub is trying to solve?

  

Whether you are a developer working on a new or existing project; a designer looking for tested specifications on typography, a product owner seeking resources for cloud native development or anyone else who is just interested in the BC Gov digital world and want to learn more, finding the things you need to get your work done can be hard. 

  

The digital landscape is constantly changing and improving. This can be challenging to keep up with if the platform for guidelines/policies is a static word document or of the like. 

  

In addition, a static guideline loses out on key information that is useful whenever working with digital products such as: 

- who authored this content?  
- when was it last updated?  
- are other teams using this guideline? 
  

In other words, can that guideline be trusted to be complete, relevant, and useful?

  
  

An additional problem the Devhub is working towards solving is spurring community around digital workflows and products. This includes events. Events in government can be scattered along different platforms which can make them difficult to discover, share and manage.

  

### How Devhub aims to solve these problems

  

The Devhub aims to solve these problems by:

  
- providing a platform that ‘centralizes’ all relevant content related to agile digital product building within government 
- maintains useful links between content such as: who the content may be geared towards, the author of the content, date of last update etc.  
- spur community to continuously improve guidelines/policies and even the devhub through the Github platform.  
- Make it easy and intuitive to find what you need to get your job done

**Comment by patricksimonian** [comment]
@sheaphillips what collection/topic do you think this should be apart of?

**Comment by sheaphillips** [comment]
Just so the world doesn't get too meta, it would be cool to have this as a "standalone" "About" page for the DevHub (accessible via footer or whatev).  For an MVP, if it's substantially easier, I'd say it's also fine to include it in an existing topic such as "Developer Tools" or "Getting Started on the DevOps platform".
