### ISSUE TITLE
IE 11 compatibility of DevHub and Design System

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#578]
Currently the DevHub and Design System and largely non functional in IE 11 (navigation doesn't work, previews aren't displayed, console errors).  While we do not expect any developers to be using IE (which has been discontinued)  as they access the DevHub, we do recognize that the Design System may see some use by users with older browsers.

Some work has been done to investigate the root of the compatibility problem, but it so far inconclusive.  The solution is probably some combination of polyfills and additional configuration of build-time babel transpiling but further experimentation is required to determine the specific changes.

Some resources that may be useful during future troubleshooting:

https://github.com/gatsbyjs/gatsby/issues/12399
https://gist.github.com/arnars/2bb1d81fc0955d57fe88a8348695f594

A related issue was report as bcgov/design-system#192.

**Comment by patricksimonian** [comment]
from what i've heard is one of the main issues is with routing. Gatsby uses @reach/router under the hood so we may have to investigate how it handles IE support (if at all)

**Comment by patricksimonian** [comment]
I've been debugging this issue and found some solutions to get MOST functionality working.

introducing ` <script src="https://cdn.polyfill.io/v2/polyfill.min.js" />` into the head of the page resolved most of the navigating issues.

With that there are several issues that still need to be resolved which should most likely have seperate issues created for them. Perhaps we should assign this as an epic. 

Known issues:

 - Collection carousels are not functional, it looks like the cards do exist within the container but are not visible at all.
 - Card descriptions do not truncate to 4 lines and overflow past the card containers
 - live design system examples are not showing up (stuck on loading)

**Comment by patricksimonian** [comment]
ofcourse instead of using a cdn we can try and consume this as an npm package
