### ISSUE TITLE
Order of collections/topics is not preserved/deterministic across builds.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#592]
Topics seem to be displayed on the home page (and in the topic list) appears to vary between builds - sometimes one topic is the first and other times, it's not even on the home page.  This will be unexpected to users.

**Comment by patricksimonian** [comment]
As of PR #581 i introduced a small function to sort collections on the front end. I chose to sort this at run time vs some type of extra configuration within the registration that does build time sorting.

This was done for several reasons, how sorting at build time may well change during the V3 Devhub Development. In addition, this functionality didn't seem like it was 100% needed as core functionality for how devhub works.
