### ISSUE TITLE
Update Topics view based on designs/mockups

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#617]
@orinevares and @dlevineBC have some great designs that we have gone over for the next iteration of the Topics page.

Do either of you mind posting those images here as comments?

**Comment by orinevares** [comment]
Sure, do you want the original sketch file as well? Whatever is easiest for you.

**Comment by orinevares** [comment]
[Topics Mockuppdf.pdf](https://github.com/bcgov/devhub-app-web/files/3163295/Topics.Mockuppdf.pdf)

**Comment by orinevares** [comment]
![Topics Mockup1pdf](https://user-images.githubusercontent.com/43620986/57473905-c4b4bd80-7245-11e9-8e49-c075c6cfc232.jpg)
![Topics Mockuppdf](https://user-images.githubusercontent.com/43620986/57473911-c67e8100-7245-11e9-9adf-58185fa0f1d9.jpg)

**Comment by patricksimonian** [comment]
awesome. @DerekSgov let's extreme program this bad boy.

**Comment by DerekSgov** [comment]
Lets do it @patricksimonian and thanks @orinevares for the mockups, they look great!

**Comment by patricksimonian** [comment]
@orinevares does the sketch file show measurements and other css specs? If so, it may help. Also we do not have sketch so are their other ways to consume the file?

**Comment by orinevares** [comment]
You could upload the sketch file into UX Pin. Otherwise I'd have to copy and paste out the individual layer CSS attributes from the sketch file on my computer.

**Comment by orinevares** [comment]
Emailing you the sketch file just in case.

**Comment by patricksimonian** [comment]
oh okay perfect, i'll take a look at that. I think i can upload it into Zeplin as well

**Comment by patricksimonian** [comment]
@orinevares did you get those sketch files to me?

**Comment by orinevares** [comment]
Yup should be in your inbox, but I'll send it over again now just in case.
