### ISSUE TITLE
Move BC DevEx logo in footer

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#619]
![Screen Shot 2019-05-09 at 10.28.46 AM.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/4fe88314-3e02-43ac-92fc-81e82d5d7c55)

DevEx logo seems like it should not be in between the other links. Thoughts?

**Comment by patricksimonian** [comment]
I think moving it to the last item would be awesome. 

<img width="941" alt="Screen Shot 2019-05-10 at 1 19 40 PM" src="https://user-images.githubusercontent.com/21046727/57554446-4ed45300-7326-11e9-9785-747946e32589.png">
