### ISSUE TITLE
Setup redirects for openshift wiki and pathfinder.gov.bc.ca to point to devhub.

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#620]
blocked by pathfinder and opensfhit content being sourced within the devhub. 

Once we have the content that was located at pathfinder and the openshift wiki, lets set up a redirect policy (moved permanently)  to reroute traffic to developer.gov.bc.ca

**Comment by patricksimonian** [comment]
@sheaphillips what do you suggest would be the best way to set up the redirects? Should we configure the devhub to be exposed by the openshift wiki / pathfinder.gov.bc.ca. Or add some config to those two services redirect over to the devhub?

**Comment by sheaphillips** [comment]
This is done for now as far as I am concerned. We can revisit once we’ve migrated more/most content.

**Comment by patricksimonian** [comment]
dropping this issue since it's already been done
