### ISSUE TITLE
Create 'Community and Events' Topic

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#658]
include these as cards:
https://developer.gov.bc.ca/Community-Enablers-and-Events/BC-Gov-Development-Community-Events
https://www.yammer.com/gov.bc.ca/
https://www.meetup.com/DevOps-Commons/
https://www.meetup.com/Cloud-Native-Victoria/
and all the events on the events page

**Comment by DerekSgov** [comment]
The Community and Events topic does not have eventbrite events in it currently, wait for V3 as it will be possible then
