### ISSUE TITLE
Devhub Issue: Government of British Columbia API Guidelines DRAFT [emoji rendering]

### ISSUE THREAD

**Issue by ll911** [bcgov/devhub-app-web#704]
> path: (do not delete) https://github.com/bcgov/api-guidelines/blob/master/government-of-british-columbia-api-guidelines.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Featured-Cards/Government-of-British-Columbia-API-Guidelines-DRAFT

**Comment by patricksimonian** [comment]
thanks for the issue. this is being resolved!

**Comment by patricksimonian** [comment]
#717
