### ISSUE TITLE
Card Duplicates on homepage search

### ISSUE THREAD

**Issue by DerekSgov** [bcgov/devhub-app-web#726]
This is caused by there being copies of the same card across different collections

![Screen Shot 2019-06-17 at 12.43.19 PM.png](https://images.zenhubusercontent.com/5cd34a8fb496d8552ec7cec3/fc54c1f4-fcd7-4583-b4d0-5d74d72d3c24)

**Comment by patricksimonian** [comment]
seems like a ux bug, as we discussed the functionality is intentional it is behaving in the correct manner. perhaps there is a creative way to show that a card belongs to many collections
