### ISSUE TITLE
Standup Discourse Instance

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#868]
Standup discourse instance based on findings from #812

**Comment by patricksimonian** [comment]
I have had significannt trouble setting up discourse locally, with docker-compose, and an openshift build.

**Comment by patricksimonian** [comment]
node bb has also been very challenging as it has a very complicated installation process that performs some very __unconventional__ node js tasks

**Comment by patricksimonian** [comment]
checking out fruum ...https://fruum.github.io/#v/home

**Comment by sheaphillips** [comment]
We've exhausted our time box (and patience) on this so we'll call it an unsuccessful exploration at this point.  If we want to pick things up again, one more option to explore is https://thredded.org - open source, Ruby based. Seems more likely to be container-friendly than Discourse and others (no "launcher", etc.)
