### ISSUE TITLE
Search Github via DevHub

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#901]
We currently have the ability to search through "local" DevHub content, as well as Rocket.Chat from the DevHub's search interface.  We want to provide an ability to search through BC Gov-related GitHub orgs, and (eventually) other sources as well. This epic related to the addition of GitHub as a search "source" for DevHub which will become the basis of other sources as well.

**Comment by patricksimonian** [comment]
this has been completed.
