### ISSUE TITLE
Compile an onboarding kit to the devhub for new team members

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#936]
This onboarding kit should be made in mind for junior dev personas. 

Somethings to keep in mind

- [x] DevHub overview/readmes

- [x]  describing project structure

- [x] describing project structure pit falls and journey map

- [x]  tech stack and resources to learn more

- [x]  unit-testing

- [x]  e2e testing (and its pitfalls)

- [x]  styled-components and its journey map

- [x]  how devhub works

- [x]  how the ci/cd pipeline works (high-level explanation on the usage of github actions and jenkins)

**Comment by patricksimonian** [comment]
## Github Flow
> by @DerekSgov 
What is GitHub Flow and How Does the DevHub Use it?

GitHub flow is a lightweight, branch-based workflow that supports teams and projects where deployments are made regularly.

When developing in GitHub flow, branches are created off of master. These branches could contain new features, bug fixes, content curation etc, and the branch names should reflect what type of work is being done and the purpose of that branch.

When working on your branch, commit early and often, with clear and concise commit messages as this will allow others on your team to understand your work more effectively and allow for better de-bugging if an issue arrises. Also try to make sure your code follows best practices and is well documented.

At some point during the development process, you will need to open a pull request for your branch. This can be either when you are almost done your work on the branch, stuck on an issue and need some advice, or really any time during the development process. This allows team members to easily see what you’re working on, give feedback and review your pull request to put it into production.

After it has been approved, you can then promote it through the various stages of the DevHubs Jenkins pipeline, with the final one putting the changes into production. After that has been done and the app is running smoothly, go back to your PR and merge it there, deleting the branch after.

What if Another Team Member Merges New Code While you’re still working?

To handle this issue, the “rebase” command is used. Rebase, similar to “merge” also integrates changes from a branch to another, but unlike merge it rewrites the commit history in order to produce a straight, linear succession of commits.

When visualized, it looks something like this

A rebase looks like this (https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase)

To implement a successful rebase, first you would make sure your master branch is up to date, then on your feature branch do the following command ‘git rebase master’, this would rebase the current production code with your changes. You will then have to make sure there are no conflicts, after that a final step of force pushing as you have previously done to create your pull request is required.

(More detailed info on how to use here https://git-scm.com/docs/git-rebase)

**Comment by patricksimonian** [comment]
## Devhub Overview

As described in the readme, the Devhub is front end application that pulls data from a variety of sources: Github, Eventbrite, Local Filesystem, and converts them into objects that are then presen ted as either standalone HTML pages, or a collection of HTML pages within a 'Topic'

A few writeups on the devhub can be found here
- [about devhub](https://developer.gov.bc.ca/aboutDevhub)
- [README.md](https://github.com/bcgov/devhub-app-web/blob/master/README.md)

**Comment by patricksimonian** [comment]
## Project Structure Pit Falls and Journey Map

You will notice the directory structure could be cleaned up and this is something we are totally aware of. 

For a journey map what I am hoping to see is:

- the complete isolation of md documents that are used as gatsby data sources into a single directory, currently we have multiple directories serving this purpose
- as components are refactored, their file/folder structure is refactored as well to adopt a new standard yet to be defined (my guess is we will use the implicit import method where all component directories will contain index.js files possibly)

**Comment by patricksimonian** [comment]
## Testing

### Unit Testing

Unit testing is done with Jest. Jest is pre-built into gatsby applications. 

#### Enzyme

Originally, our jest unit tests were interfacing with Enzyme, a react testing utility library but there were incompatibilities with Enzyme and React 16 features. __We are no longer writing tests using enzyme__. The plan is to deprecate its usage and remove the library altogether. 

#### @testing-library/react

We are using testing library in place of Jest. This testing library has several benefits as described by the author of the repo. The tests now behave more like how a user would interact with a component which really helps to nail down what spec we are testing for. 

> more info here https://github.com/testing-library/react-testing-library

**Comment by patricksimonian** [comment]
## Tech Stack

These are the following technologies and __key libraries__ that the Devhub is using. Please note that there may be libraries that are being deprecated. 

- Gatsby JS https://www.gatsbyjs.org/
- React (Gatsby leverages React) https://reactjs.org/
- GraphQL (Gatsby leverages GraphQL, *gatsby has great tutorials on graphql*) https://graphql.org/
- Styled Components with Emotion JS https://emotion.sh/docs/introduction
- Jest for unit testing https://jestjs.io/
- Cypress for E2E testing https://cypress.io

**Comment by patricksimonian** [comment]
## Styled Components

### What are they?
Styled Components is a way of creating __React Components__ that have CSS styles embedded at them. More than that, they provide a way to create isolated, programmable, and composable styles.

There are a couple of styled component libraries currently dominating NPM at the moment and they are `styled-components` and `emotion`. We are using __emotion__. Emotion has improved performance and utility over styled components. When and if one of these libraries get's deprecated in favor of the 'winning' one, the api for both libraries will seamlessly integrate as they both use string template functions to create styles. 

### What about CSS Modules?

In the early days of Devhub, we were utilizing a styling technique called `CSS Modules`. You may notice some component files with a stylesheet named something like `component.module.css`. 
This was a great way to create isolated styles but had a few drawbacks. 

- Stylesheets were still in vanilla CSS (so no logic or themes could be embedded). 
- More files being created per component make organization clunky. 

### Journey Map

Since we are in the _inbetween_ stages of CSS Modules and Styled Components. All future styles should utilize _styled components_. If you are working on a component that uses CSS Modules, please convert it to emotion.js

**Comment by patricksimonian** [comment]
## Project Structure

The root application structure looks somethinng like this. 

```
.
├── app-web
├── .jenkins
├── .pipeline
├── docs
├── functional-tests
├── matomo
├── openshift
└── pipeline
```

## app-web 
This is where the Gatsby Project lives and where you will most likely be spending your time working in

## .jenkins
This is the [bcdk](https://github.com/bcdevops/bcdk) jenkins configuration and pipeline (including all jobs for other projects without our openshift namespace)

## .pipeline
This is the [bcdk](https://github.com/bcdevops/bcdk) pipeline for the devhub gatsby project

## docs
Misc docs in regards to the project

## functional tests
This is the `BDD` stack which is currently not in use and may be cleaned up. 

## matomo
This is all the infra code required to support the matomo instance in our tools namespace

## openshift
This is all the infra code required to support the devhub, the `.pipeline` folder references this code 

## pipeline
This is the gradle runner for the BDD stack which, again, may be removed shortly since we are not using BDD stack

**Comment by patricksimonian** [comment]
## How the Devhub Works

### Introduction

The Devhub has a couple of primary functions. These are:

1. To get content from a variety of sources and display them in meaningful ways on the site. This content can be from markdown files, links to HTML sites, Eventbrite and more

2. To index these sources for searchability as well as provide a means to search external sources such as _Rocket.Chat_, _Github_

This document will discuss in detail how data is sourced; how it is annotated in different ways with metadata to make meaningful connections between data points; how the data is indexed; and lastly, how external search sources are made available.

**Comment by patricksimonian** [comment]
## CI/CD Pipeline

We are currently leveraging two different pipelines to accomplish CI and CD. 

Continuous Integration is done with __Github Actions__. 

Although not continuous, our deployment to Openshift is accomplished with Jenkins.

## Github Actions and Journey Map

Github actions have been an excellent way for us to offload some heavy lifting to check unit and integration tests. In addition, the PR clearly displays whether tests passed or not which is a bonus. 

To modify the Github Action, you can navigate to the `.github` folder inside of the repo (on Github) and go through the GUI. 

__Currently__ we are blocked on running E2E tests with Github Actions. For some reason, we are getting some issues with utilizing the Cypress docker image. This appears to be a known issue and hopefully gets resolved shortly. 

## Jenkins Pipeline and Road Map.

Jenkins is responsible for building and deploying our images to each namespace in the Devhub Project Set. It also does extra things like provision a keycloak client during dev deploys. 

There are some things left to be desired with Jenkins which we will hope to work on:
- automatic pr merge after clean up stage
- setting up sonarqube for static code analysis

**Comment by w8896699** [comment]
https://www.gatsbyjs.org/tutorial/part-one/ 
I found that this Gatsby official document is really helpful.

**Comment by patricksimonian** [comment]
# Algolia Production Account

Our team account is registered under my email. If you require access to the production Algolia account please contact me :)
