### ISSUE TITLE
Events page is loading slow

### ISSUE THREAD

**Issue by lukegonis** [bcgov/devhub-app-web#948]
Matomo is taking a long time to establish a connection. Requires discussion.

**Comment by patricksimonian** [comment]
Are these events on Devhub or Matomo?

**Comment by patricksimonian** [comment]
From https://developer.gov.bc.ca/events, it looks like the sheer amount of components that are rendered is what is causing the slowdown. For now, our fix will be to remove historical events and reintroduce them in the upcoming sprint.
