### ISSUE TITLE
Compile Disaster Recovery Instructions

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-app-web#961]
This should include instructions on 
- how to standup the Devhub in Openshift
- how to standup Jenkins in Openshift

**Comment by w8896699** [comment]
Some of the instructions belongs to bcdk repo.

**Comment by patricksimonian** [comment]
where we are at in our troubleshooting is we require the ability to login to our clusters registry to pull images and then push them into minishift. This process should be documented so we can create some content around local development with openshift/okd
