### ISSUE TITLE
For external links, consider implementing a persistent DevHub nav bar/other widget that "stays with" users when they click an external link from within DevHub

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/devhub-app-web#998]
In working with a topic that is mostly made up of external links, I noticed that the UX is not great since all DevHub context is lost once the external link is clicked.  One idea would be to implement some kind of UI element that would stay on the screen when users click on external links, and provide 1) the DevHub context they are in (e.g. which Topic/search) and 2) provides an easy way to get back to that context of another spot in DevHub.  This could be similar to the way that some sites - commonly web template sites (such as HTM5UP) off the top of my head - retain a nav bar when you click on "view preview".  The user can bypass/disable this, but it is there by default.

**Comment by patricksimonian** [comment]
closing as this is stale
