### ISSUE TITLE
https://developer.gov.bc.ca/Requesting-a-SSO-Realm-to-be-created

### ISSUE THREAD

**Issue by kelpisland** [bcgov/devhub-app-web#999]
**Describe the bug**
Page Issues:

- Odd caps and typo: "new REALM IN OpenShift iRH SSO please "

- "Rocket.Chat #devops-requests" should link to https://developer.gov.bc.ca/Steps-to-join-Pathfinder-Rocket.Chat

- No link to add an issue

**Comment by patricksimonian** [comment]
Billy maybe we can fit this into one of our upcoming prs

**Comment by patricksimonian** [comment]
the following content issues have been fixed in the openshift-wiki repo

**Comment by patricksimonian** [comment]
https://github.com/BCDevOps/openshift-wiki/blob/master/docs/RH-SSO/RequestSSORealm.md

**Comment by patricksimonian** [comment]
These changes will be reflected on the next deployment of Devhub :)
